name: Synchronize labels
on:
  push:
    branches: [master]
    paths: [.github/workflows/github.labeler.yaml, .github/labels.yaml]

jobs:
  sync:
    name: Synchronize labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # renovate: tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yaml
          prune: true
