name: Security hardening (Github Actions workflows)

on:
  pull_request:
    types: [opened, synchronize]
    paths: [".github/workflows/**"]

jobs:
  ci_harden_security:
    name: Security hardening
    permissions:
      security-events: write
    uses: xunleii/github-actions-grimoire/.github/workflows/security.workflows.yaml@42f3d38aa983309e49769c5ef3736746bb1ddf39
